services:
  - type: web
    name: sistema-miller
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python seed.py && gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
